### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ghost** [SapuSeven/BetterUntis#109]
<details>
<summary>Crash Log</summary>

```
Request ID: 3
Error code: 3
Error message: k.b.x.e: Unexpected JSON token at offset 667: Expected '{, kind: a'.
 JSON input: .....te":"2021-07-11"}],"timeGrid":null}}}

```
</details>

**Comment by SapuSeven** [comment]
I'm kinda stuck on this one.
I assume you are trying to log in to your account.

The problem is that for some reason Untis doesn't provide a timegrid for your user account, which means the App won't know how to draw the timetable.

Theoretically I'd be able to work out a solution, but I need some more details. Can you share which school you are logging in to?
