### ISSUE TITLE
[Bug Report] Outdated Timetable List

### ISSUE THREAD

**Issue by Domi04151309** [SapuSeven/BetterUntis#113]
**Description**

_The timetable selection dialog displays the available timetables of the year before (the year the user was logged in).
For example, the user logged in when he was in grade 8 but is now in grade 9. The dialog will display grade 8 as accessible which is a false positive. When trying to access grade 8 or 9 it says no permission for timetable._

**Screenshots**

| BetterUntis | Original App |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/36272047/93331029-fb2e1f80-f81f-11ea-885b-fdd1f9aa0a9b.jpeg"/> | <img src="https://user-images.githubusercontent.com/36272047/93331052-01240080-f820-11ea-9d53-8af4a88a018b.jpeg"/> |

**Additional information**

 - Android version: _10_
 - BetterUntis version: _3.2.2-DEBUG(21)_
 - Installation source: _Own Build_

**Comment by SapuSeven** [comment]
Right, that happens when the user data from Untis changes. It's only downloaded when you log in, so it will never update...

To force an update, edit the affected profile and login without changing anything.

A potential fix would be to use the schoolYears in the user data and update the data if a new school year begins.

**Comment by Domi04151309** [comment]
This will also result in the class being displayed as `?` for every lesson.
