### ISSUE TITLE
[Feature Request] Filter by Subjects

### ISSUE THREAD

**Issue by Redstonecrafter0** [SapuSeven/BetterUntis#157]
Hi.

As in the title I want to request the feature to filter the personal timetable also by subjects.
In my case the whole class has one Untis account and it shows me subjects I don't have because of this like Spanish or French.

**Comment by mjg** [comment]
Same here, or even worse: In the "collegiate phase" (last 2 years of highschool in Germany), students can pick their subjects individually (within restraints). If your school uses a single account for the class (or, as in our case: for all students) then you see mostly irrelevant information because you can filter by class/year only so far.

Yes, this is a request to work around a suboptimal untis usage by the school...

**Comment by TheGreyDiamond** [comment]
Same issues here, this is really an oversight and I don't get why the stock untis app can't do this

**Comment by danielgoldbach68** [comment]
This issue is massively understated. My app CRASHES as my school has so many individual lessons next to each other. Someone in the school management was to lazy to give students their own account, and just crammed all of the entire grade into one class. While Better Untis is the only app that crashes, the other apps are also terrible, as you would need to search 10min to find all your lessons. 

PLEASE BRING THE ABILITY TO FILTER BY SUBJECTS. Switching to BetterUntis would be a no-brainer.


![Screenshot_20210913-151908](https://user-images.githubusercontent.com/52566328/133092124-846d28ba-7615-404c-8240-f769173dfc34.png)
Ridiculous timetable, crashes after 2 seconds!

![Screenshot_20210913-151855](https://user-images.githubusercontent.com/52566328/133092144-c74ffc7d-1117-4392-afc7-b445b59fb6bc.png)
Shown error message

![Screenshot_20210913-152518](https://user-images.githubusercontent.com/52566328/133092165-ae2fc206-d01f-4ee7-88b5-4520fc7861f7.png)
Official app (also terrible, since they REMOVED the function to colour the subjects differently, which would have helped.

Also due to the crashes, I will report an error referring to this thread.

**Comment by lm41** [comment]
The linked pull request adds the ability to filter subjects. Can you check [this artifact](https://output.circle-artifacts.com/output/job/08a476a0-209e-48f0-a9af-d6f8ee658537/artifacts/0/outputs/apk/debug/app-debug.apk) if this was helpful and drop suggestions in the linked pull request.

You can access the filter in Settings -> Timetable -> Display Options -> Subjects to hide

**Comment by SapuSeven** [comment]
To be implemented - see #102/#361
