### ISSUE TITLE
[Feature Request] Update the wiki on how to authenticate the user now.

### ISSUE THREAD

**Issue by Chuaat** [SapuSeven/BetterUntis#219]
**Update the wiki on how to authenticate the user now**

Update the wiki with the new changes of the units mobile API, including the changed way of authentication.

**Comment by SapuSeven** [comment]
I'm not sure what wiki entry you mean. The API calls mostly stayed the same, the only thing that changed is the URL the API is accessed with.

**Comment by Chuaat** [comment]
Sorry, my bad, I understood the conversation in #201 wrong. So if I'm right, you now use `mobileServiceUrl` for android and ios if their respective `useMobileServiceUrl` is true, and else you use `https://mobile.webuntis.com/ms/app/<schoolid>/jsonrpc_intern.do`?

**Comment by SapuSeven** [comment]
Not quite.

Each login request now looks at the school info object returned from school search.

You correctly assumed that `mobileServiceUrl` is used as-is if `useMobileServiceUrl` is true.

Otherwise however, `serverUrl` is used as a base URL and modified to include `/jsonrpc_intern.do` in the path (e.g.
`https://euterpe.webuntis.com/WebUntis?school=demo-school` becomes
`https://euterpe.webuntis.com/WebUntis/jsonrpc_intern.do?school=demo-school`).

The `mobile.webuntis.com` URL was used in previous versions of the app and actually caused all the latest crashes, it seems that Untis doesn't allow using this endpoint any more.

**Comment by Chuaat** [comment]
Thanks for the explanation, this confirms that my feature request is invalid.
