### ISSUE TITLE
Release APK on Github Releases

### ISSUE THREAD

**Issue by MatsG23** [SapuSeven/BetterUntis#320]
It would be great if APKs could be released alongside the source for each release for people who don't want to get their apps through an app store.
I have noticed that you have already done that earlier but I think you stopped doing that. The last Github Release was on 02th December 2020 (Version 3.4.4), while the version in the Google Play Store is 3.5.1 (from 9th September 2022).

**Comment by lm41** [comment]
You can always get the latest release on this site: https://sapuseven.com/app/BetterUntis/

**Comment by MatsG23** [comment]
Thanks for the tip! Is it somehow RSS-parsable so that I notice a new versio
-------- Original-Nachricht --------
Am 29. Okt. 2022, 21:19, schrieb Lars Mühlbauer :

**Comment by lm41** [comment]
I don't know much about RSS.

SapuSeven: Maybe we should consider providing an in app update for all apps that are not signed by F-Droid or G-Play, but with your own keys. If you feel the same way, then you can add this to the list for the Material 3 update. Maybe like [newpipe](https://github.com/TeamNewPipe/NewPipe/blob/b607a0912519e0099c04313962b7820f13a253f6/app/src/main/java/org/schabi/newpipe/NewVersionWorker.kt) did this

**Comment by SapuSeven** [comment]
As @lm41 mentioned, the current build pipeline deploys releases to sapuseven.com.
I also recently made an update to the pipeline to automatically create a GitHub release with the APK file, but I didn't publish an update since, so the next update should already be uploaded with the next GitHub release.
All of the auto-built APKs (Website, GH Releases) use the same key for signing and should be interchangeable in terms of updates.

As for RSS: There is already a GitHub official feed you can use: [https://github.com/SapuSeven/BetterUntis/releases.atom](https://github.com/SapuSeven/BetterUntis/releases.atom)
