### ISSUE TITLE
[Bug Report] Support for Parents / Legal Guardians

### ISSUE THREAD

**Issue by W113565456** [SapuSeven/BetterUntis#325]
<details>
<summary>Logs</summary>

```
Anfragen-ID: 5
Fehlercode: -7001
Fehlermeldung: invalid element type: 12
```
</details>

**Additional information**

- Android version: _10_
- BetterUntis version: _3.5.1 (34)_
- Installation source: _com.android.vending_

**Comment by SapuSeven** [comment]
Hi, could you please describe how and when exactly this error occurs?
What happens if it does - does the app crash?

**Comment by W113565456** [comment]
When starting the app, no timetable is displayed, but the error

**Comment by SapuSeven** [comment]
Alright, this seems to be connected to another Untis API change.

I looked into the original app code and noticed there are additional element types for Parents/Legal Guardians, which are not supported by BetterUntis at the moment.
I implemented these types in the Material 3 Update (#290), but this might need some further work. For now, please wait until the new version is released.

**Comment by lm41** [comment]
@W113565456 is this still an issue? Can you please check with the latest release?

**Comment by jolly-jump** [comment]
Had the same Issue with above version.

Tried https://api.sapuseven.com/apps/betteruntis/artifact/release/4.0.0-beta04

now it shows "unexpected end of stream" or similar when aktivating the profile using the QR code.

The login seems to work after that, but shows no time table at all. When pulling down to reload, it "loads" endlessly.

I accepted to use detailed logs and sentry. But since the option "show error logs" is gone in this version, I do not know if some information was sent via sentry.

**Comment by lm41** [comment]
Can you please try [this](https://output.circle-artifacts.com/output/job/a34f15fe-5f98-4ee9-8b9b-8d19ff308b20/artifacts/0/outputs/apk/debug/app-debug.apk) artifact?

**Comment by user0-07161** [comment]
> Can you please try [this](https://output.circle-artifacts.com/output/job/a34f15fe-5f98-4ee9-8b9b-8d19ff308b20/artifacts/0/outputs/apk/debug/app-debug.apk) artifact?

It Crashes when i starting It.

**Comment by jolly-jump** [comment]
Hi. I would like to open this again.
The login with the parent account does work with 4.0.0 release (and beta 4 before that).
Still: it shows no default time table. When pulling down to reload, it "loads" endlessly.

I can add a time table for the class my child is in, but since there are differences between the class schedule and the individual schedule of the pupil, I guess that there should be a default schedule for the parent (i.e. for the individual - belonging - child).

What can I help to debug this?
