### ISSUE TITLE
[ALPHA] Make subject block non-transparent

### ISSUE THREAD

**Issue by MatsG23** [SapuSeven/BetterUntis#330]
### Problem Statement

You can see the stripes behind each subject block.

### Solution Ideas

Set the transparancy to none.

**Comment by SapuSeven** [comment]
This is merely the default value. When you edit the color of past lessons in settings, you can use the alpha slider at the bottom to adjust the transparency.

I opted for this default look because the background color is also configurable - if the user selects a light/dark background there's no need to adjust the past item color to match the new theme.
Also I think it looks nice to see lessons "fade into the past" :)

**Comment by MatsG23** [comment]
You are right! I just felt like this was a bug when using the app.
