### ISSUE TITLE
[Bug Report]  Notifications about upcoming classes can't be dismissed

### ISSUE THREAD

**Issue by dr460nf1r3** [SapuSeven/BetterUntis#365]
### Steps to Reproduce

1. Use the latest BetaUntis apk
2. Turn on notifications for upcoming classes
3. Wait a few hours for new notifications to arrive

### Expected Result

The notification should be either:
1. Hiding itself after the class ended
2. Be dismissable

### Actual Result

Notifications aren't dismissable, which means that multiple notifications are present at the same time. 

### Android Version

Android 13 (CrDroid)

### BetterUntis Version

4.0.0-beta03

### Installation Source

None

### Additional information

The installation source is the download available at GitHub.

**Comment by SapuSeven** [comment]
The notifications are persistent by design so you don't accidentally swipe them away. Usually they go away after the next lesson starts, but for some reason this is broken in the latest beta release. I was already able to reproduce it and I'm working on a solution.
Meanwhile you can manually dismiss the notifications using "clear all notifications" in the BetterUntis notification settings.

**Comment by dr460nf1r3** [comment]
Hiding them automatically sounds perfect. 

Btw - great job on implementing MD3, the newest BetaUntis versions definitely look marvellous! 😊

**Comment by SapuSeven** [comment]
I pushed a fix in 0bc135b6219e5f4f2cfe027e961c1888a98b4bb1.
Please try this build: [BetterUntis v4.0.0-beta03-DEBUG+27967111.1109](https://api.sapuseven.com/apps/betteruntis/artifact/debug/1109).

**Comment by dr460nf1r3** [comment]
Thanks! I'll be able to provide feedback on Thursday.

**Comment by lm41** [comment]
This is fixed, notifications are deleted again after the break (or after the hour, so precisely I have not observed)

**Comment by dr460nf1r3** [comment]
It is also fixed on my side. Thanks for the fix!
