### ISSUE TITLE
Drawer is opening though it shouldn't

### ISSUE THREAD

**Issue by Lijucay** [SapuSeven/BetterUntis#370]
### Steps to Reproduce

Scroll on the right side of the screen (it takes a few tries until it does what it should not do)

### Expected Result

The drawer should not open when scrolling on the right half of the screen

### Actual Result

The drawer sometimes opens when scrolling on the right half of the screen

### Android Version

Android 13

### BetterUntis Version

4.0.0-beta03-DEBUG

### Installation Source

None

### Additional information

Installation source: GitHub (it was not selectable here)

**Comment by SapuSeven** [comment]
That's interesting, I haven't been able to reproduce this yet. Can you see any kind of pattern that causes this behavior?
Maybe you can also try and create a screen recording with visible touch location? It's very hard to fix the issue without this or a reliable way to reproduce.

**Comment by Lijucay** [comment]
Sure. I'll give my best ^^

**Comment by Lijucay** [comment]
Sure. I'll give my best ^^

https://user-images.githubusercontent.com/104652374/227624043-7b23c762-cf54-4c2d-9afb-ac04f8f08f7e.mp4

**Comment by Lauritz-Tieste** [comment]
The Android Navigation Drawer can be opened by swiping at the edge of the screen by default. Since this happens accidentally when scrolling through the timetable, it should be deactivated.

https://stackoverflow.com/questions/17051104/disable-the-swipe-gesture-that-opens-the-navigation-drawer-in-android
