### ISSUE TITLE
Seperation der "Vespätungen" und "Abwesenheiten", wie in der Untis App

### ISSUE THREAD

**Issue by sagik-cf** [SapuSeven/BetterUntis#371]
### Problem Statement

Die Verspätungen aber auch die Abwesenheiten sind in der selben Spalte zu finden

### Solution Ideas

Beides trennen

**Comment by SapuSeven** [comment]
Please provide screenshots from the original Untis app as a comparison.

**Comment by cookiegruemel** [comment]
> Please provide screenshots from the original Untis app as a comparison.
Idk in my original App its all in one. 
![Screenshot_20230517_104217_Untis Mobile](https://github.com/SapuSeven/BetterUntis/assets/75181498/e5d78de0-bbc8-449a-bcd1-3d398255ef02)

**Comment by SapuSeven** [comment]
I believe the Units API doesn't differentiate between being late and being absent. If that's the case, it's really difficult to determine because you don't know what the last lesson for the student was. The app would need to load the personal timetable for each absence, which would be both slow and unreliable.
As long as the official app doesn't have this feature, it's unfortunately not possible to include in BetterUntis.
