### ISSUE TITLE
[Feature Request] Automatische Stundenplanzusammensetzung

### ISSUE THREAD

**Issue by auer-lukas** [SapuSeven/BetterUntis#381]
### Problem Statement

Es wäre Vorteilhaft, wenn BetterUntis das Feature anbieten würde, den Stundenplan von Räumen oder Lehrpersonen, bei unzureichenden Rechten, aus den Klassenstundenplänen zusammensetzt.

An meiner Schule haben wir lediglich das Zugriffsrecht auf die Stundenpläne aller Klassen - daraus könnte man jedoch alle anderen  ableiten.

**Comment by new-on-github** [comment]
Normally the school should change the rights in the Untis-Admin-Interface. Than every teacher can see the timetable form every other teacher. 

Or do you need this feature because your admin don't want to give the rights for this to every teacher? This would be then a technical solution for a social problem, correct?

**Comment by auer-lukas** [comment]
Yes, that's right. Our admin only gives out the rights to see class-timetables. 
And I think that I'm not the only student that doesn't have the right to view the room and teacher's timetables lol ;)

**Comment by new-on-github** [comment]
> Yes, that's right. Our admin only gives out the rights to see class-timetables. And I think that I'm not the only student that doesn't have the right to view the room and teacher's timetables lol ;)

Ok, you are a student and not a teacher... But normally you should not be able to see the timetables from all classes. This is a misconfiguration from the admin's side. Therefore I don't think someone will fix this feature-request for you.

But if you solve it yourself, maybe a pull request will be accepted...

**Comment by auer-lukas** [comment]
It's not a misconfiguration - just a thing that came up during the past few years to help students coordinating projects with several classes. ;)

**Comment by new-on-github** [comment]
> It's not a misconfiguration - just a thing that came up during the past few years to help students coordinating projects with several classes. ;)

Ok, and what will happen, if you admin knows that you use this right to retrieve all the data from this? 

I think a foss-project should also be concerned about moral aspects, but maybe I am wrong.

**Comment by auer-lukas** [comment]
Nothing would happen because I could look through all the different timetables and create one for a room or teacher, if I want to. But it costs a lot of time to do it - so it'd just be a simple feature and has nothing to do with moral haha - but I understand your point

**Comment by new-on-github** [comment]
> Nothing would happen because I could look through all the different timetables and create one for a room or teacher, if I want to. 

I am not sure. If I gave you my key to open a special classroom and you opened other rooms or even made a second key for you, I wouldn't give you the key. Therefore, in my opinion, the possibility to do something is not the right to do it. 

But I will stop the discussion from my side because this should be a place for technical solutions. Maybe someone will even help you with this.

**Comment by SapuSeven** [comment]
Thanks for your initial discussion.
I think this sort of feature is outside the scope of this app, so I probably won't work on this myself.
However, I'm happy to support if anyone else wants to work on this feature.
