### ISSUE TITLE
[Bug Report] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [SapuSeven/BetterUntis#395]
Since versionCode is [not static anymore](https://github.com/SapuSeven/BetterUntis/blob/4.0.0/app/build.gradle#L26) newer versions were not picked up automatically.

Is there a reason to have different versionCodes for/from the same code built at a different hour?

Now, first issue, Sentry key missing when trying to build 4.0.0:
```
> Task :app:uploadSentryProguardMappingsRelease FAILED
> compressing mappings
> uploading mappings
error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

> Task :app:l8DexDesugarLibRelease

0 problems were found storing the configuration cache.

See the complete report at file:///home/vagrant/build/com.sapuseven.untis/build/reports/configuration-cache/ga1mgi17vi7qah3znxmjbdwu/8d0xuk5dr9dl1afa8wj7ogmir/configuration-cache-report.html

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:uploadSentryProguardMappingsRelease'.
> Process 'command '/tmp/.sentry-cli10692983813887660774.exe'' finished with non-zero exit value 1
```

Second issue, 4.0.1 can't even be tried since mlkit is not FOSS: https://github.com/SapuSeven/BetterUntis/commit/0f336a5eaaf96cd7e6fe8155f9dc73b5a9720fad

**Comment by SapuSeven** [comment]
Previously, the version code changed manually with each new released version.
However, when developing the Material 3 Update, I added the ability to test early versions using a Private Testing Track on Google Play.
This needed a new release published to Google Play for each build. But those builds would have used the same version code. This didn't work for Google Play where each release needed to have a new version code.
I also couldn't run a separate version numbering track because version codes need to always be ascending.
For those reasons, I decided to update the version code to be calculated based on build time. That way, each build will always have a new, higher version code.

I will look into the issues with F-Droid builds.
With regards to the ml-kit dependency, I will try to find a solution, because it is not strictly required (There's a very simple backup scanner).
BTW The reason for switching the code scanner is that the originally used library for that had some publishing issues and couldn't be downloaded on build time.

**Comment by SapuSeven** [comment]
Thing is, I'm not an F-Droid user and I don't really know how to correctly configure everything.

I created a new branch, `fdroid` - It adds two flavors: `gms` and `foss`. The `foss` flavor doesn't include the GMS dependencies.

As for the mapping upload issue (from stack trace): This would be resolved by excluding the corresponding Gradle task like this: `-x uploadSentryProguardMappingsRelease`

I'd greatly appreciate the help of anyone who knows how to correctly setup the [F-Droid metadata file](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.sapuseven.untis.yml) to handle these changes and also the dynamic version code.

**Comment by SapuSeven** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13652
F-Droid metadata update has been submitted.
The F-Droid store should receive the 4.x updates soon.

**Comment by SapuSeven** [comment]
Merged 🎉
